name: Bandit Security Analysis

on:
  push: # Trigger when code is pushed
    branches:
      - main
  pull_request: # Trigger for pull requests targeting the main branch

jobs:
  security-analysis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python and specify the version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Replace with your project's Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Install Bandit
      - name: Install Bandit
        run: pip install bandit

      # Step 5: Run Bandit for security analysis
      - name: Run Bandit
        run: bandit -r . # Recursively analyze the current directory

      # Step 6: (Optional) Optimize Bandit configuration
      # Use a Bandit config file to suppress false positives or exclude specific directories/files
      - name: Run Bandit with config (Optional)
        run: bandit -r . -c .bandit.yml
        # Ensure you have a .bandit.yml file in your repository
